#
# Managed by Ansible
#
groups:
  - name: system down
    rules:
      - alert: InstanceDown
        expr: 'up{job="netdata"} == 0'
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Host down: {{ $labels.host }}"
          description: "{{ $labels.host }} of job {{ $labels.job }} has been down for more than 5 minutes."

      # https://www.robustperception.io/alerting-on-gauges-in-prometheus-2-0
      - alert: InstanceDownAVG
        expr: 'avg_over_time(up{job="netdata"} [5m]) <= 0.9'
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Host down: {{ $labels.host }}"
          description: "{{ $labels.host }} of job {{ $labels.job }} has been down for more than 5 minutes."

      - alert: HostNotUp
        expr: count(up{host!=""} offset 1h) by (host,job) unless count(up{host!=""}) by (host,job)
        for: 5m
        labels:
          team: ops
          severity: critical
        annotations:
          summary: "Host not up {{ $labels.host }}"
          description: |-
            Host shut down? Missing updates for metric 'up' of host '{{ $labels.host }}' from '{{ $labels.job }}'
            The up metric has no current value but was available an hour ago.

  - name: cpu
    rules:
      - alert: HighCPU
        expr: 'sum(netdata_system_cpu_percentage_average{dimension!~"idle"}) by (host) > 80'
        for: 4m
        labels:
          severity: warning
        annotations:
          summary: "High CPU on {{ $labels.host }}"
          description: "{{ $labels.host }} CPU usage was above 80 for more than 4 minutes"

  - name: filesystem
    rules:
      - alert: DiskUsagePercentage
        expr: |
          (
            sum by (host, family)(netdata_disk_space_GiB_average{dimension="used", family!~"/boot/efi|/dev/shm|/run|/dev|/run/lock|/var/lib/lxd.*"})
            /
            sum by (host, family)(netdata_disk_space_GiB_average{})
          )
          * 100
          > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Disk Full on {{ $labels.host }}"
          description: "{{ $labels.host }}:{{ $labels.family }} filesystem with usage above 90% for longer than 5 minutes "

      - alert: DiskSpacePrediction36h
        expr: |
          predict_linear(
            netdata_disk_space_GiB_average{dimension="avail", family!~"/boot/efi|/dev/shm|/run|/dev|/run/.*|/var/lib/lxd.*"}
            [36h], 3600 * 36
            )
          < 5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "36h Disk space prediction low on {{ $labels.host }}"
          description: "Diskspace is predicted to get below 5GiB on host {{ $labels.host }} for mountpoint {{ $labels.family }}, prediction based on the last 36h"

      - alert: DiskSpacePrediction72h
        expr: |
          predict_linear(
            netdata_disk_space_GiB_average{dimension="avail", family!~"/boot/efi|/dev/shm|/run|/dev|/run/.*|/var/lib/lxd.*"}
            [36h], 3600 * 72
            )
          < 5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "72h Disk space prediction low  on {{ $labels.host }}"
          description: "Diskspace is predicted to get below 5GiB on host {{ $labels.host }} for mountpoint {{ $labels.family }}, prediction based on the last 36h"

      - alert: DiskInodesPrediction72h
        expr: |
          predict_linear(
            netdata_disk_inodes_inodes_average{dimension="avail", family!~"/boot/efi|/dev/shm|/run|/dev|/run/.*|/var/lib/lxd.*"}
            [36h], 3600 * 72
            )
          < 20000
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "72h Inodes prediction low {{ $labels.host }}"
          description: "Inodes is predicted to get below 20'000 on host {{ $labels.host }} for mountpoint {{ $labels.family }}, prediction based on the last 36h"

      - alert: MdRaidDiskFailed
        expr: 'netdata_md_health_failed_disks_average > 0'
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Mdraid failed disk on {{ $labels.host }}"
          description: "Mdraid failed disk on {{ $labels.host }} {{ $labels.dimension }} "

  - name: ram
    rules:
      - alert: LowMemoryAvailable
        expr: |
          sum by (host)(netdata_mem_available_MiB_average)
          /
          sum by (host)(netdata_system_ram_MiB_average)
          *100
          < 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low Mem available on host {{ $labels.host }}"
          description: "{{ $labels.host }} available RAM was below 5% for more than 5 minutes"

  # - name:
  #   rules:
  #   - alert:
  #     expr: ' > 80'
  #     for: 2m
  #     annotations:
  #       description: "{{ $labels.host }} "
  #       summary: "{{ $labels.host }}"
