{
 "title": "Blackbox Exporter (HTTP prober)",
 "description": "Blackbox exporter HTTP prober dashboard",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(probe_success, job)"
    }
   },
   {
    "name": "group",
    "query": {
     "query": "label_values(probe_success{job=~\"$job\"}, group)"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(probe_success{job=~\"$job\",group=~\"$group\"}, environment)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(probe_success{job=~\"$job\",group=~\"$group\",environment=~\"$environment\"}, instance)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "HTTP Probe Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{job=~\"$job\", group=~\"$group\", environment=~\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "probe_http_ssl{job=~\"$job\", group=~\"$group\", environment=~\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "(\n  probe_ssl_earliest_cert_expiry{job=~\"$job\", group=~\"$group\", environment=~\"$environment\", instance=~\"$instance\"} \n  - \n  time()\n) / 3600 / 24"
    },
    {
     "expr": "probe_http_status_code{job=~\"$job\", group=~\"$group\", environment=~\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(probe_duration_seconds{job=~\"$job\", group=~\"$group\", environment=~\"$environment\", instance=~\"$instance\"}[1m])"
    },
    {
     "expr": "probe_tls_version_info{job=~\"$job\", group=~\"$group\", environment=~\"$environment\", instance=~\"$instance\"}"
    },
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds{job=~\"$job\", group=~\"$group\", environment=~\"$environment\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "timeseries",
   "description": "Returns how long the probe took to complete in seconds",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(\n    probe_duration_seconds{\n        job=~\"$job\", \n        group=~\"$group\", \n        environment=~\"$environment\", \n        instance=~\"$instance\"\n    }\n[$__rate_interval]) > 0",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HTTP Status [$__interval]",
   "type": "state-timeline",
   "description": "HTTP Response Code History",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "# show highest http code > 200\nmax_over_time(\n    probe_http_status_code{job=~\"$job\", group=~\"$group\", environment=~\"$environment\", instance=~\"$instance\"} \n) > 200\n# fallback to min (0=error or else 200 OK)\ndefault\nmin_over_time(\n    probe_http_status_code{job=~\"$job\", group=~\"$group\", environment=~\"$environment\", instance=~\"$instance\"} \n)\ndefault\n# default show probe_sucess value\nmin_over_time(\n    probe_success{job=~\"$job\", group=~\"$group\", environment=~\"$environment\", instance=~\"$instance\"}\n) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }, "repeat": "instance" },
  {
   "title": "HTTP Probe Phases Duration",
   "type": "timeseries",
   "description": "Duration of http request by phase, summed over all redirects",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{job=~\"$job\", group=~\"$group\", instance=~\"$instance\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  }
 ]
}