{
 "title": "Docker Logs Dashboard",
 "tags": [
  "docker",
  "logs",
  "validation",
  "victorialogs"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DS",
    "query": "victoriametrics-logs-datasource"
   },
   { "name": "host", "label": "host", "query": { "query": "" } },
   { "name": "compose_project", "label": "project", "query": { "query": "host:in($host)" } },
   {
    "name": "compose_service",
    "label": "service",
    "query": {
     "query": "host:in($host) and compose_project:in($compose_project)"
    }
   },
   { "name": "log_query", "label": "Query" },
   { "name": "serverlogs_query", "label": "Server Query" },
   { "name": "adhoc", "label": "filter" }
  ]
 },
 "panels": [
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 },
   "options": {
    "content": "# VictoriaLogs Dashboard\n\n* [LogsQL](https://docs.victoriametrics.com/victorialogs/logsql/index.html)\n* [LogsQL Examples](https://docs.victoriametrics.com/victorialogs/logsql-examples/)\n* [Querying on CLI](https://docs.victoriametrics.com/victorialogs/querying/) \n* [logsQL.py CLI helper](https://github.com/teamapps-org/ansible-collection-teamapps-general/blob/main/roles/victorialogs/files/logsQL.py), [README](https://github.com/teamapps-org/ansible-collection-teamapps-general/blob/main/roles/victorialogs/files/README.md)"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 1 },
   "options": {
    "content": "## Example Queries for ad hoc log analysis\n### filter\n* `error -exception` all messages containing the [word](https://docs.victoriametrics.com/victorialogs/logsql/index.html#word-filter) \"error\", but not \"exception\"\n* `\"[123]: cannot open file\"` exact [phrase filter](https://docs.victoriametrics.com/victorialogs/logsql/index.html#phrase-filter)\n* `~\"err|warn\"` substring / [regex filter](https://docs.victoriametrics.com/victorialogs/logsql/#regexp-filter). case sensitive!\n* `err*`,`'unexpected fail'*` [prefix filter](https://docs.victoriametrics.com/victorialogs/logsql/#prefix-filter)\n* `i('err*')` [case insentive filtering](https://docs.victoriametrics.com/victorialogs/logsql/index.html#case-insensitive-filter), LogsQL supports [quoting](https://docs.victoriametrics.com/victorialogs/logsql/#string-literals) via double quotes `\"`, single quotes `'` and backticks `\n* `compose_service: gitlab` apply word filter on specific field.\n* `compose_service:~ \"git.+\"` apply regex filter on field\n*  No field specified (above) is just a shortcut for `_msg: <filter>`\n* `| stream_context before 2 after 5` show [context](https://docs.victoriametrics.com/victorialogs/logsql/#stream_context-pipe) lines before/after matching messages\n\n### extract & format\n* `| extract \"ip=<ip> \"` [extract fields](https://docs.victoriametrics.com/victorialogs/logsql/#extract-pipe) from message with pattern\n* `| unpack_json` [parse json](https://docs.victoriametrics.com/victorialogs/logsql/#unpack_json-pipe) from msg to fields\n* `| unpack_logfmt` [parse logfmt](https://docs.victoriametrics.com/victorialogs/logsql/#unpack_logfmt-pipe) from msg\n* `| format \"request from <ip>:<port>\"` change output [format](https://docs.victoriametrics.com/victorialogs/logsql/#format-pipe)\n* `| format if (ip:* and host:*) \"request from <ip>:<host>\"` only [reformat line if](https://docs.victoriametrics.com/victorialogs/logsql/#conditional-format) it contains these fields\n\n* `| unpack_logfmt | status:>300 status:<400` parse log message, then apply [range comparison filter](https://docs.victoriametrics.com/victorialogs/logsql/#range-comparison-filter) on extracted field\n\n### Ad Hoc Filtering\n\nClicking a log message shows the available fields, (+) or (-) buttons can be used to quickly add add hoc filters"
   }
  },
  { "title": "Container Logs Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "overview by host [$__interval]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "category:in(dockerlogs) AND host:in($host) AND compose_project:in($compose_project) AND compose_service:in($compose_service) $log_query\n  | stats by (host) count()",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "overview by host",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "category:in(dockerlogs) AND host:in($host) AND compose_project:in($compose_project) AND compose_service:in($compose_service) $log_query\n  | stats by (host) count() logs",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "overview by compose_service [$__interval]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "category:in(dockerlogs) AND host:in($host) AND compose_project:in($compose_project) AND compose_service:in($compose_service) $log_query\n| format 'UNDEFINED' as compose_service keep_original_fields\n| stats by (compose_service) count()",
     "legendFormat": "{{ compose_service }}"
    }
   ]
  },
  {
   "title": "overview by host and project",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "category:in(dockerlogs) AND host:in($host) AND compose_project:in($compose_project) AND compose_service:in($compose_service) $log_query\n  | stats by (host,compose_project) count() logs",
     "legendFormat": "{{ host }}:{{ compose_project }}"
    }
   ]
  },
  {
   "title": "unfiltered logs (without custom Query), stacked [$__interval]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "category:in(dockerlogs) AND host:in($host) and compose_project:in($compose_project) and compose_service:in($compose_service)\n  | stats by(host) count()",
     "legendFormat": "{{ host }} {{ compose_project }}"
    }
   ]
  },
  {
   "title": "top 20 by host, compose_service",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "category:in(dockerlogs) AND host:in($host) AND compose_project:in($compose_project) AND compose_service:in($compose_service) $log_query\n  | stats by(host, compose_project, compose_service) count() logs \n  | sort by(logs) desc | limit 20",
     "legendFormat": "{{ host }}:{{ compose_service }}"
    }
   ]
  },
  {
   "title": "Container Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "type": "logs",
     "gridPos": { "h": 22, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "category:in(dockerlogs) AND host:in($host) AND compose_project:in($compose_project) AND compose_service:in($compose_service) $log_query\n| sort\n# format outputs with color codes\n| format \"\\033[33m<host>\\033[0m:\\033[36m<compose_project>\\033[0m/\\033[96m<compose_service>\\033[0m\\t<_msg>\" as _msg",
       "legendFormat": "{{ compose_service }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Unfiltered Container Logs (of selected host, project, service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "type": "logs",
     "gridPos": { "h": 22, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "category:in(dockerlogs) AND host:in($host) AND compose_project:in($compose_project) AND compose_service:in($compose_service) \n# $log_query\n| sort\n# format outputs with color codes\n| format \"\\033[33m<host>\\033[0m:\\033[36m<compose_project>\\033[0m/\\033[96m<compose_service>\\033[0m\\t<_msg>\" as _msg",
       "legendFormat": "{{ compose_service }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Serverlogs Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "overview by host [$__interval]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "host:in($host) AND category:in(serverlogs) $serverlogs_query\n  | stats by (host) count()",
       "legendFormat": "{{ host }}"
      }
     ]
    },
    {
     "title": "overview by host",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "host:in($host) AND category:in(serverlogs) $serverlogs_query\n  | stats by (host) count() logs",
       "legendFormat": "{{ host }}"
      }
     ]
    },
    {
     "title": "overview by systemd_unit [$__interval]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 14, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "host:in($host) AND category:in(serverlogs) $serverlogs_query\n| format 'UNDEFINED' as systemd_unit keep_original_fields\n| stats by (systemd_unit) count()",
       "legendFormat": "{{ systemd_unit }}"
      }
     ]
    },
    {
     "title": "overview by host and systemd_unit",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "host:in($host) AND category:in(serverlogs) $serverlogs_query\n| format 'UNDEFINED' as systemd_unit keep_original_fields\n| stats by (host,systemd_unit) count()",
       "legendFormat": "{{ host }}:{{ systemd_unit }}"
      }
     ]
    },
    {
     "title": "unfiltered logs (without custom Server Query), stacked [$__interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "host:in($host) AND category:in(serverlogs)\n| stats by (host,systemd_unit,filename) count()",
       "legendFormat": "{{ host }} {{ systemd_unit }} {{ filename }}"
      }
     ]
    },
    {
     "title": "top 20 by host, service",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "host:in($host) AND category:in(serverlogs) $serverlogs_query\n  | stats by(host, systemd_unit, filename) count() logs \n  | sort by(logs) desc | limit 20",
       "legendFormat": "{{ host }}:{{ systemd_unit }}{{ filename }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Server Logs (journald, /var/logs)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "type": "logs",
     "gridPos": { "h": 22, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "host:in($host) AND category:in(serverlogs) $serverlogs_query\n| sort\n# format outputs with color codes\n| format \"\\033[33m<host>\\033[0m:\\033[36m<job>\\033[0m:\\033[96m<systemd_unit><filename>\\033[0m\\t<_msg>\" as _msg",
       "legendFormat": "{{ compose_service }}"
      }
     ]
    }
   ]
  }
 ]
}