{
 "title": "NVMe Dashboard",
 "description": "NVMe Storage Device Health Dashboard, data from nvme_metrics.py",
 "tags": [
  "nvme",
  "smart",
  "health"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "datasource", "query": "prometheus" },
   { "name": "host", "label": "host", "query": { "query": "label_values(nvme_info,host)" } },
   {
    "name": "device",
    "query": {
     "query": "label_values(nvme_info{host=~\"$host\"}, device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Devices",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "last_over_time(nvme_info{host=~\"$host\"}[$__range])"
    }
   ]
  },
  {
   "title": "Health Status",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "last_over_time(\n    nvme_controller_ready{host=~\"$host\", device=~\"$device\"}\n[$__range])",
     "legendFormat": "{{ device }}"
    },
    {
     "expr": "last_over_time(\n    nvme_controller_enabled{host=~\"$host\",device=~\"$device\"}\n[$__range])"
    },
    {
     "expr": "last_over_time(\n    nvme_smart_media_errors{host=~\"$host\",device=~\"$device\"}\n[$__range])"
    },
    {
     "expr": "last_over_time(\n    nvme_smart_unsafe_shutdowns{host=~\"$host\",device=~\"$device\"}\n[$__range])"
    },
    {
     "expr": "last_over_time(\n    increase(nvme_smart_num_err_log_entries{host=~\"$host\",device=~\"$device\"} [1d])\n[$__range])"
    },
    {
     "expr": "last_over_time(\n    nvme_smart_percent_used{host=~\"$host\",device=~\"$device\"}\n[$__range])"
    },
    {
     "expr": "last_over_time(\n    nvme_smart_avail_spare{host=~\"$host\",device=~\"$device\"}\n[$__range])"
    },
    {
     "expr": "last_over_time(\n    sum by (host, device) ({__name__=~\"nvme_critical_warning.*\", host=~\"$host\",device=~\"$device\"})\n[$__range])"
    },
    {
     "expr": "last_over_time(\n    nvme_smart_power_cycles{host=~\"$host\",device=~\"$device\"}\n[$__range])"
    },
    {
     "expr": "last_over_time(\n    nvme_smart_power_on_hours{host=~\"$host\",device=~\"$device\"}\n[$__range])\n*3600"
    },
    {
     "expr": "last_over_time(\n    nvme_temperature_celcius{host=~\"$host\",device=~\"$device\"}\n[$__range])"
    },
    {
     "expr": "last_over_time(\n    nvme_data_bytes_written{host=~\"$host\",device=~\"$device\"}\n[$__range])"
    },
    {
     "expr": "last_over_time(\n    nvme_physical_size{host=~\"$host\",device=~\"$device\"}\n[$__range])"
    },
    {
     "expr": "last_over_time(\n    nvme_used_bytes{host=~\"$host\",device=~\"$device\"}\n[$__range])"
    },
    {
     "expr": "last_over_time(\n    nvme_used_bytes{host=~\"$host\",device=~\"$device\"}\n[$__range])\n/\nlast_over_time(\n    nvme_physical_size{host=~\"$host\",device=~\"$device\"}\n[$__range])"
    }
   ]
  },
  {
   "title": "Critical Errors",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "last_over_time(\n    sum by (__name__)({host=~\"$host\",device=~\"$device\",__name__=~\"nvme_critical_warning_.*\"})\n[$__range])",
     "legendFormat": "{{ host }} {{ device }} {{__name__}}"
    },
    {
     "expr": "last_over_time(\n    {host=~\"$host\",device=~\"$device\",__name__=~\"nvme_critical_warning_.*\"} != 0\n[$__range])",
     "legendFormat": "{{ host }} {{ device }} {{__name__}}"
    }
   ]
  },
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Data units read rate",
   "type": "timeseries",
   "description": "data units read",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(nvme_smart_data_units_read{host=~\"$host\",device=~\"$device\"} [$__interval])*1000",
     "legendFormat": "{{ host }} {{ device }}"
    }
   ]
  },
  {
   "title": "Data units written rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(nvme_smart_data_units_written{host=~\"$host\",device=~\"$device\"} [$__interval])*1000",
     "legendFormat": "{{ host }} {{ device }}"
    }
   ]
  },
  {
   "title": "Data read rate",
   "type": "timeseries",
   "description": "data bytes read",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(nvme_data_bytes_read{host=~\"$host\",device=~\"$device\"} [$__interval])",
     "legendFormat": "{{ host }} {{ device }}"
    }
   ]
  },
  {
   "title": "Data written rate",
   "type": "timeseries",
   "description": "data bytes written",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(nvme_data_bytes_written{host=~\"$host\",device=~\"$device\"} [$__interval])",
     "legendFormat": "{{ host }} {{ device }}"
    }
   ]
  },
  {
   "title": "Read Commands Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(nvme_smart_host_read_commands{host=~\"$host\",device=~\"$device\"} [$__interval])",
     "legendFormat": "{{ host }} {{ device }}"
    }
   ]
  },
  {
   "title": "Write Commands rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(nvme_smart_host_write_commands{host=~\"$host\",device=~\"$device\"} [$__interval])",
     "legendFormat": "{{ host }} {{ device }}"
    }
   ]
  },
  {
   "title": "Used Bytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvme_used_bytes{host=~\"$host\",device=~\"$device\"}",
     "legendFormat": "{{ host }} {{ device }} "
    }
   ]
  }
 ]
}